config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
	sessions: 'users/sessions',
	registrations: 'users/registrations'
  }
  resources :posts
  resources :users, only: [ :show , :index ] do
	member do
	  get :friends, :requests
	end
  end
  resources :notifications, only: [ :destroy, :index ]
  resources :likes, only: [ :create, :destroy ]
  resources :comments, only: [ :create, :destroy, :update ]
  resources :friendships, only: [ :create, :update, :destroy ]
  root "static_pages#home"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable

  # Associations
  has_many :posts, dependent: :destroy
  has_many :requested_friendships, class_name: "Friendship", foreign_key: :requester_id, dependent: :destroy
  has_many :friends, through: :requested_friendships, source: :requestee
  has_many :received_friendships, class_name: "Friendship", foreign_key: :requestee_id, dependent: :destroy
  has_many :received_friends, through: :received_friendships, source: :requester
  has_many :notifications, dependent: :destroy, foreign_key: :user_id
  has_many :sent_notifications, class_name: "Notification", dependent: :destroy, foreign_key: :sender_id
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  # Validations
  validates_presence_of :name, :last_name

  ################
  # User methods #
  ################

  def full_name
	"#{self.name} #{self.last_name}"
  end

  def request_friendship(other_user)
	# send friend request, no need to send friends: false, since default is set to false in the db
	if good_to_go?(other_user)
	  self.requested_friendships.create(requestee_id: other_user.id) if good_to_go?(other_user)
	  if !other_user.notifications.where(sender_id: self.id, title: "request", message:
										"#{self.name.capitalize} #{self.last_name.capitalize} wants to be friends with you.").any?
		other_user.notifications.create(sender_id: self.id, title: "request", message:
										"#{self.name.capitalize} #{self.last_name.capitalize} wants
										to be friends with you.")
	  end
	end
  end

  # True when friends = true, false otherwise
  def has_friendship?(other_user)
	!get_friendship(self, other_user).nil?
  end

  # When friends = false and a request has already been sent
  def has_requested?(other_user)
	!get_request(other_user, self).nil?
  end

  # Returns true when current user requested the friendship
  def requested_to?(other_user)
	has_requested?(other_user) && get_request(other_user, self).requester == self ? true : false
  end

  # Status of relationship
  def status(other_user)
	if has_friendship?(other_user)
	  return "friends"
	elsif has_requested?(other_user)
	  if requested_to?(other_user)
		return 'i_requested'
	  else
		return 'i_received'
	  end
	end
  end

  # Returns the relationship, a Friendship object
  def get_relationship(other_user)
	get_request(other_user,self).nil? ? get_friendship(self,other_user) : get_request(other_user,self)
  end

  # current_user accepts a friend request from other_user
  def accept_friend_request(other_user)
	friendship = get_request(other_user, self)
	if friendship
	  friendship.update_attributes(friends: true)
	  other_user.notifications.create(sender_id: self.id, title: "accept_request", message: "You are now friends with #{self.name.capitalize} #{self.last_name.capitalize}.")
	end
  end

  # current_user rejects a friends request from other_user
  def reject_friend_request(other_user)
	friendship = get_request(other_user, self)
	friendship.destroy if friendship
  end

  # Removes current relation between current_user and other_user
  def delete_friendship(other_user)
	get_friendship(self, other_user).destroy if has_friendship?(other_user)
  end

  # Returns ActiveRecord::Relation with all his friends(those with friends = true)
  def get_all_friends
	friends_requested_ids = "SELECT requestee_id FROM friendships WHERE requester_id = :user_id AND friends = true"
	friends_received_ids  = "SELECT requester_id FROM friendships WHERE requestee_id = :user_id AND friends = true"
	User.where("id IN (#{friends_requested_ids}) OR id IN (#{friends_received_ids})", user_id: self.id)
  end

  # Returns ActiveRecord::Relation with all friendships requests(received not made)
  def get_all_requests
	friends_received_ids  = "SELECT requester_id FROM friendships WHERE requestee_id = :user_id AND friends = false"
	User.where("id IN (#{friends_received_ids})", user_id: self.id)
  end

  # Returns the feed of the current user
  def feed
	friends_requested_ids = "SELECT requestee_id FROM friendships WHERE requester_id = :user_id AND friends = true"
	friends_received_ids  = "SELECT requester_id FROM friendships WHERE requestee_id = :user_id AND friends = true"
	Post.where("user_id IN (#{friends_requested_ids}) OR user_id in (#{friends_received_ids}) OR user_id = :user_id", 
			   user_id: self.id).order(created_at: :desc)
  end

  private

	# Returns the request that `from` has made to `to`
	def get_request(from, to)
	  from.requested_friendships.find_by(requestee_id: to.id, friends: false) ||
		to.requested_friendships.find_by(requestee_id: from.id, friends: false)
	end

	# Returns an ActiveRecord::Relation[Friendship] with the current friendship if any
	def get_friendship(current_user, other_user)
	  current_user.requested_friendships.find_by(requestee_id: other_user.id, friends: true) ||
		other_user.requested_friendships.find_by(requestee_id: current_user.id, friends: true)
	end

	# Check that current_user and other_user aren't friends and that friend requests haven't been sent
	def good_to_go?(other_user)
	  get_friendship(self,other_user).nil? && get_request(other_user, self).nil?
	end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_sign_up_params, only: [:create]
  before_filter :configure_account_update_params, only: [:update]

  def new
	super
  end

  def create
	super
  end

  def edit
	super
  end

  def update
	super
  end

  def destroy
	super
  end

  def cancel
	super
  end

  protected

	def configure_sign_up_params
	  devise_parameter_sanitizer.for(:sign_up).push(:name, :last_name)
	end

	def configure_account_update_params
	  devise_parameter_sanitizer.for(:account_update).push(:name, :last_name)
	end

	def after_sign_up_path_for(resource)
	  super(resource)
	end

	def after_inactive_sign_up_path_for(resource)
	  super(resource)
	end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_filter :configure_sign_in_params, only: [:create]

  def new
	super
  end

  def create
	super
  end

  def destroy
	super
  end

  protected

	def configure_sign_in_params
	  devise_parameter_sanitizer.for(:sign_in) << :attribute
	end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [ :show, :friends, :requests ]

  def show
	@posts = @user.posts.paginate(page: params[:page], per_page: 15)
  end

  def index
	@users = User.paginate(page: params[:page]).order(created_at: :desc)
  end

  def friends
	@friends = @user.get_all_friends
  end

  def requests
	@requests = @user.get_all_requests
  end

  private

	def find_user
	  @user = User.find(params[:id])
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_accept_friendship_form.html.haml
#accept_friendship_form
  = form_for(current_user.get_relationship(@user), html: { method: :patch , remote: true }) do |f|
    .hidden
      = hidden_field_tag :other_user_id, @user.id
    = f.submit message, class: "btn btn-success"

app/views/users/_friendship_button.html.haml
#form
  - case current_user.status(@user)
    - when "friends"
      = render partial: "remove_friendship_form", locals: { message: "Remove friendship" }
    - when "i_requested"
      = render partial: "remove_friendship_form", locals: { message: "Cancel request" }
    - when "i_received"
      = render partial: "accept_friendship_form", locals: { message: "Accept friendship" }
      = render partial: "remove_friendship_form", locals: { message: "Decline request" }
    - else
      = render "send_request_form"

app/views/users/_remove_friendship_form.html.haml
#remove_friendship_form
  = form_for(current_user.get_relationship(@user), html: { method: :delete , remote: true}) do |f|
    .hidden
      = hidden_field_tag :other_user_id, @user.id
    = f.submit message, class: "btn btn-danger"

app/views/users/_send_request_form.html.haml
#send_request_form
  = form_for(current_user.requested_friendships.build, html: { remote: true }) do |f|
    .hidden
      = hidden_field_tag :requestee_id, @user.id
    = f.submit "Add friend", class: "btn btn-primary"

app/views/users/_user_posts.html.haml
- @posts.each do |post|
  %li{:id => "post-#{post.id}"}
    .post
      = link_to gravatar_for(post.user, size: 50), post.user
      %span.user
        = link_to "#{post.user.name.capitalize} #{post.user.last_name.capitalize}", post.user
      %span.timestamp
        %i.fa.fa-clock-o
        Posted #{time_ago_in_words(post.created_at)} ago.
        - if current_user == post.user
          = link_to "delete", post, method: :delete, remote: true
      %br
      %span.content
        = post.body
      %hr.full-line
      .bottom-links
        %span#like_form
          - if post.liked_by?(current_user)
            = render "likes/nope", object: post
          - else
            = render "likes/like", object: post
    #comments
      - if post.comments.any?
        - post.comments.each do |comment|
          %div{ id: "comment-#{comment.id}" }
            .comment
              .clearfix
                .pull-left
                  %p.com-author
                    = link_to "#{comment.user.name.capitalize} #{comment.user.last_name.capitalize} said: ", comment.user
                .pull-right
                  - if current_user == comment.user
                    = link_to "delete", comment, method: :delete, remote: true
              %p.com-body
                = comment.body
    .comment-form
      = render "comments/form", object: post

app/views/users/_user_stats.html.haml
%p
  = link_to "Friends:", friends_user_path(@user)
  = @user.get_all_friends.count

app/views/users/friends.html.haml
- @friends.each do |friend|
  = friend.full_name

app/views/users/index.html.haml
.row
  .col-md-6.col-md-offset-3
    .requests
      %h1 Friendship requests received
      - @users.each do |user|
        %h2
          %span
            = gravatar_for(user, { size: 80 })
          = link_to user.full_name, user_path(user)
      = will_paginate @users, renderer: BootstrapPagination::Rails

app/views/users/requests.html.haml
.row
  .col-md-6.col-md-offset-3
    .requests
      %h1 Friendship requests received
      - @requests.each do |user|
        %h2
          %span
            = gravatar_for(user, { size: 80 })
          = link_to user.full_name, user_path(user)

app/views/users/show.html.haml
.container.clear-top.user-profile
  .row
    .col-md-3
      = gravatar_for(@user, { size: 280 })
      %br
      %h4= @user.full_name
      - if current_user != @user
        - if user_signed_in?
          = render "friendship_button"
      - else
        You have
        = @user.get_all_requests.count
        friendship requests
      #users_stats
        = render "user_stats"
    .col-md-9
      %h2
        User timeline
      %ul
      = render "user_posts"
      = will_paginate @posts, renderer: BootstrapPagination::Rails