config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
	sessions: 'users/sessions',
	registrations: 'users/registrations'
  }
  resources :posts
  resources :users, only: [ :show , :index ] do
	member do
	  get :friends, :requests
	end
  end
  resources :notifications, only: [ :destroy, :index ]
  resources :likes, only: [ :create, :destroy ]
  resources :comments, only: [ :create, :destroy, :update ]
  resources :friendships, only: [ :create, :update, :destroy ]
  root "static_pages#home"
end

app/views/layouts/_header.html.haml
.navigation-bar
  .container
    .brand.pull-left
      %ul.left-menu
        %li.main-odin
          %a(href= root_path)
            %i.fa.fa-facebook-official
        - if user_signed_in?
          %form(role="search")
            %input.form-control(type="text" placeholder="Search for friends...")
        - else
          %li
            %h3
              %a(href="#") OdinBook
    .navigation-links.pull-right
      - if user_signed_in?
        %ul.right-menu
          %li
            = link_to "Users", users_path
          %li
            %a(href=root_path)
              %i.fa.fa-home
          %li.dropdown
            %a.dropdown-toggle(data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="#")
              %i.fa.fa-flag
              %i.fa.fa-caret-down
            %ul.dropdown-menu.pull-right
              - if current_user.notifications.any?
                - current_user.notifications.each do |notification|
                  %li
                    = link_to "#{notification.message}", notification_path(notification), method: :delete
              - else
                %li
                  = link_to "You don't have notifications", "#"
          %li.dropdown
            %a.dropdown-toggle(data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="#")
              %i.fa.fa-user
              %i.fa.fa-caret-down
            %ul.dropdown-menu
              %li
                = link_to "Requests received", requests_user_path(current_user)
              %li
                = link_to "View profile", user_path(current_user)
              %li
                = link_to "Edit profile", edit_user_registration_path
              %li
                = link_to "Sign out", destroy_user_session_path, method: :delete
      - else
        %a(href="#") Welcome!

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Odin Book
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    - flash.each do |message_type, message|
      %div{ class: "alert alert-#{message_type}" }
        = message
    = yield